# Generated by Django 4.2.4 on 2023-09-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp_library', '0004_genre_description_genre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, max_length=512, null=True, serialize={'col_css_class': 'col-12'}),
        ),
    ]
